### ISSUE TITLE
It wont load

### ISSUE THREAD

**Issue by Sharingan69420** [Sjnez613/RenoSense-Rewrite#14]
![unknown](https://user-images.githubusercontent.com/93792325/140563899-0ef0dcd6-662f-468f-a43c-f408810a7345.png)

It just stays like that and dont respond

**Comment by Sharingan69420** [comment]
Oyvey is not compatible with it, great client

**Comment by jraffstar** [comment]
its not compatible with oyvey because renosense is lliterally phobos and oyvey = phobos but worse
