### ISSUE TITLE
pasted

### ISSUE THREAD

**Issue by k3lan** [Sjnez613/RenoSense-Rewrite#2]
I noticed that this is just OyVey with a new name. I don't know if this was a mistake by the developers but renaming OyVey 0.0.3 to RenoSense doesn't necessarily make it a "rewrite." I genuinely hope this was a mistake on the developers as you can literally get OyVey anywhere else.

Salutations, Kelan D.

**Comment by tvffty** [comment]
🤓

**Comment by Sjnez613** [comment]
🤓
