### ISSUE TITLE
color issues

### ISSUE THREAD

**Issue by CrystalPvpFan** [Sjnez613/RenoSense-Rewrite#4]
color is buggy af
and add step

**Comment by Sjnez613** [comment]
I added step, can you tell me what is wrong with the colors?

**Comment by CrystalPvpFan** [comment]
basiclly for oyvey autocrystal the color picker doesnt work

**Comment by CrystalPvpFan** [comment]
also after u relaunch mc the colors for packetmine render breaks

**Comment by CrystalPvpFan** [comment]
i found the issue the issue is when u change the color of the clickgui it breaks the color system
